### ISSUE TITLE
Error Linking Unigen Executable

### ISSUE THREAD

**Issue by allrtaken** [meelgroup/unigen#1]
Hi Mate,

I was trying to build Unigen from source but encountered an error. In particular, after successfully building and install both CMS and ApproxMC, I was running make for Unigen when I got the following error:

> [100%] Linking CXX executable ../unigen
> CMakeFiles/unigen-bin.dir/main.cpp.o: In function `main':
> /home/adi/Downloads/UniGen4/src/main.cpp:390: undefined reference to `ApproxMC::AppMC::set_reuse_models(unsigned int)'

The detailed logs are in the attached files. I can also send build logs of apmc and cms if needed. I used fresh clones of cms and apmc. Any pointers would be appreciated.

Thanks!
Aditya
[unigen_cmake.txt](https://github.com/meelgroup/unigen/files/5100921/unigen_cmake.txt)
[unigen_make.txt](https://github.com/meelgroup/unigen/files/5100922/unigen_make.txt)

**Comment by msoos** [comment]
Hi,

I believe you need to upgrade your ApproxMC :) Can you please delete all parts of old ApproxMC (e.g. from `/usr/local/lib` and from `/usr/lib` and `/usr/lib64/` and `/usr/local/lib64`), including the headers (from `/usr/local/include` and `/usr/include`), and delete the old build directory of ApproxMC (this is **really** important, as CMake registers build directories and will use this if you don't delete it, even if it's not installed!). Then please re-clone ApproxMC and build it again :)

Let us know if it worked -- I just checked, the current system online should build without a hitch :) I hope the above helped,

Mate

**Comment by allrtaken** [comment]
Hi,

I just did a complete reinstall with all the steps you mentioned, taking care to delete everything that was previously created (including the library files, include files and build directory), but it still gives the same error. I had the same problem on another machine earlier too btw.

I was checking approxmc.cpp and I noticed that 
> void AppMC::set_reuse_models(uint32_t reuse_models)

is not preceded by
> DLL_PUBLIC

unlike other functions in that file. Could this be the reason for the undefined reference? Apologies in case this is trivial or absurd -- I just thought it would be better to bring it to your attention.

Thanks!

**Comment by allrtaken** [comment]
That fixed it -- I manually added DLL_PUBLIC to that line (line 156 in approxmc.cpp) and the unigen installation went through without any problems :)

Thanks!

**Comment by msoos** [comment]
Oh wow! Great catch! I'll fix this tonight :) Thank you so much!

Mate

**Comment by msoos** [comment]
Fixed, thanks so much! I thanked you in the commit, too :)

Cheers,

Mate
