### ISSUE TITLE
Static Binary

### ISSUE THREAD

**Issue by allrtaken** [meelgroup/unigen#10]
Hello,

Is it possible to also get the static binary with the latest release? It would be very helpful to quickly set up on new machines instead of going through the entire build process.

Thanks!
Aditya

**Comment by msoos** [comment]
Hi,

I have now updated the UniGen README to add the following.

You must compile all of CryptoMiniSat, ApproxMC, and UniGen with the `cmake` argument `-DSTATICCOMPILE=ON` and then issue `make`. You should build these new, or things may not work (cmake is weird). That's all. It works 100% of the times, I have used this many times. This will generate a static binary. You must compile ALL of them with this argument. Good luck,

Mate
