### ISSUE TITLE
Install and import pyunigen

### ISSUE THREAD

**Issue by izzayacine** [meelgroup/unigen#14]
I successfully installed pyunigen with pip command, but when I try to import the module I get this error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyunigen.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '__ZNK5CMSat9SATSolver38serialize_solution_reconstruction_dataEv'

I get the same message in Linux and Mac OS.

**Comment by msoos** [comment]
Ooops, thank you so much for the bug report! I have now kicked off a new PyPI build. There should be a new 2.5.6 package built and released on PyPI soon (it's automatic). Can you please check in about 30m-1h if the new version is released? If it's released, it should work! If not, can you please let me know and I'll look into it :) Thanks again,

Mate

**Comment by izzayacine** [comment]
It works now. Thanks

**Comment by msoos** [comment]
Nice! Thank you again, this kind of feedback REALLY helps!
