### ISSUE TITLE
Parameters to Sampler

### ISSUE THREAD

**Issue by alexeyignatiev** [meelgroup/unigen#16]
Hi guys,

Another issue I am not sure about is whether parameters `epsilon`, `delta`, and `kappa` are still a thing. You don't list them explicitly among the other parameters of the constructor like `verbosity` and `seed`. But they are still mentioned in the doc-string of the class.

Alexey

**Comment by msoos** [comment]
Hi,

Thanks for that note! I have now fixed this as per above commit :) All these values are extremely important an significantly alter the behaviour of the system. The text simply did not display it, however, all internal code and all python-specific code dealt with, and cared for, these values. I hope this fixes the issue!

Mate

PS: The build broke but I'm about to fix it :)

**Comment by alexeyignatiev** [comment]
Thanks, @msoos! I thought those parameters should be important but they were missing in the list of parameters, which was a bit surprising. So I decided to ask.

**Comment by alexeyignatiev** [comment]
Hey @msoos. It looks all good, I've added access to it from PySAT. Please let me know if something in the [documentation](https://pysathq.github.io/docs/html/api/allies/unigen.html) makes no/little sense. :)

**Comment by msoos** [comment]
NICE, thank you so much! I owe you a beer next time we meet! Are you planning to go to CAV in 2024? I'll be Montreal Canada, it'll be great and the city beautiful I'm sure :)

**Comment by alexeyignatiev** [comment]
Well, at this point I don't have a plan to submit anything to CAV. But I'll do my best to find a way to get the promised beer, haha. 😀

**Comment by msoos** [comment]
Ah, sad! Okay, well, the beer will have to wait for another conference then :smile: Thanks again! :heart:

**Comment by kuldeepmeel** [comment]
Thanks @alexeyignatiev. Btw, would you be interested in adding cmsgen as well: https://github.com/meelgroup/cmsgen

It's really fast and also does well in practice: https://www.msoos.org/2021/09/cmsgen-a-fast-uniform-like-sampler/

**Comment by alexeyignatiev** [comment]
I agree the more tools integrated the better. And this one looks interesting. I just need to understand what exactly the tool does and find time to add it. 😃 Alternatively, an additional hand would be appreciated!

**Comment by msoos** [comment]
Good point. Okay I'll take a shot at it. I find it hard to do this kind of Python magic but I'll try :) Maybe I'll learn some cool skill :)

**Comment by alexeyignatiev** [comment]
Thanks, @msoos. There is no magic there - just boring routine. :) Also, implementation-wise everything is simple.
