### ISSUE TITLE
References can not be found

### ISSUE THREAD

**Issue by l8l** [meelgroup/unigen#17]
When clicking on the references provided in the readme (namely http://comp.nus.edu.sg/~meel/Papers/cav20-sgm.pdf and https://www.comp.nus.edu.sg/~meel/bib/SGM20.bib and https://www.comp.nus.edu.sg/~meel/bib/CFMSV15a.bib and https://www.comp.nus.edu.sg/~meel/bib/CMV14.bib), I am redirected to "404 - Page not found" pages.

**Comment by msoos** [comment]
Sorry. @kuldeepmeel This is an issue for all stuff that was linked to your NUS page. I think we should link all of these to either to my page, or to a domain that's not controlled by an institution, but is controlled by us. That's likely the only long-term viable solution, so things don't break too much. We could do GitHub as well, e.g. `meelgroup/papers` or something?

**Comment by kuldeepmeel** [comment]
Yeah, I am sorry -- this is entirely my fault. I like the idea of having a repo as that's independent of the institutes. Will work on it. 
For now, I pointed them to cs.toronto.edu address.

**Comment by l8l** [comment]
Perfect, thanks! 
Alternatively, one could also upload the papers on arxiv and let the links point there.
Unigen is a really nice program. Keep the great work up = )

**Comment by msoos** [comment]
Thanks 💛Have you tried using cmsgen?

https://github.com/meelgroup/cmsgen

It’s only uniform-LIKE without guarantees but it’s crazy fast and often
better than other samplers without guarantees.

Just a hint in case you don’t need  guarantees :)

Mate

**Comment by msoos** [comment]
BTW, I just made a new release of cmsgen, you can download a linux/mac/windows binary now. I hope that helps,

Mate

**Comment by l8l** [comment]
Thanks a lot! That is good to know = )

**Comment by msoos** [comment]
Yay, references have been updated, I am closing.

Thank you so much for reporting!
