### ISSUE TITLE
Building via the Dockerfile - CMake Version Error

### ISSUE THREAD

**Issue by bhayat-quantinuum** [meelgroup/unigen#19]
When building via the Dockerfile, I receive the error below. My docker build command is:

`docker build .`

```
> ERROR [builder 27/31] RUN cmake -DSTATICCOMPILE=ON ..                  0.1s
------
 > [builder 27/31] RUN cmake -DSTATICCOMPILE=ON ..:
0.132 CMake Error at CMakeLists.txt:21 (cmake_minimum_required):
0.132   CMake 3.12 or higher is required.  You are running version 3.5.1
0.132 
0.132 
0.132 -- Configuring incomplete, errors occurred!
------

 1 warning found (use docker --debug to expand):
 - FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1)
Dockerfile:50
--------------------
  48 |     RUN mkdir build
  49 |     WORKDIR /home/solver/unigen/build
  50 | >>> RUN cmake -DSTATICCOMPILE=ON ..
  51 |     RUN make -j6 \
  52 |         && make install
--------------------
ERROR: failed to solve: process "/bin/sh -c cmake -DSTATICCOMPILE=ON .." did not complete successfully: exit code: 1
```

If I change the base image to `ubuntu:20.04`, I get past this issue, but then run into others:

```
0.764 CMake Error at CMakeLists.txt:94 (find_package):
0.764   Could not find a package configuration file provided by "sbva" with any of
0.764   the following names:
0.764 
0.764     sbvaConfig.cmake
0.764     sbva-config.cmake
```

```
2.062 -- Could NOT find arjun (missing: arjun_DIR)
2.062 CMake Error at CMakeLists.txt:458 (message):
2.062   Cannot find Arjun.  Please install it! Exiting.
```

**Comment by msoos** [comment]
Hi,

Sorry, Dockerfile is no longer supported. However, UniGen is definitely possible to build using well-documented method. Please see the GitHub workflow file: https://github.com/meelgroup/unigen/actions/runs/11523689688/workflow

That should build without a hitch. Sorry that Dockerfile is no longer supported. Please let me know if you have any trouble using it via that build process. I'm keeping this open so you can report any issues you encounter building using the workflow file. Of course it's quite easy to make a Docker image out of that workflow, so if you would like to contribute that back as a PR, I'd be super happy!

Mate

**Comment by bhayat-quantinuum** [comment]
Hello @msoos!

Thanks for the response. When attempting to follow the build from the workflow, I run into an issue when building `arjun`.

```
2.339 CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
2.339   Could NOT find MPFR (missing: MPFR_INCLUDES MPFR_LIBRARIES MPFR_VERSION_OK)
2.339   (Required is at least version "1.0.0")
2.339 Call Stack (most recent call first):
2.339   /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
2.339   cmake/FindMPFR.cmake:106 (find_package_handle_standard_args)
2.339   CMakeLists.txt:384 (find_package)
```

Here is the relevant section of my updated Dockerfile:

```
#build arjun
WORKDIR /
RUN git clone https://github.com/meelgroup/arjun
WORKDIR /arjun
RUN mkdir build
WORKDIR /arjun/build
RUN cmake -DSTATICCOMPILE=ON ..
RUN make -j6 \
    && make install
```

Regards

**Comment by msoos** [comment]
Hi,

You need to install MPFR as noted in the error. I hope this helps,

Mate

**Comment by bhayat-quantinuum** [comment]
Managed to successfully build docker image. Thanks for you help. Will create a PR shortly.

**Comment by msoos** [comment]
Nice, thanks, looking forward!
