### ISSUE TITLE
Parallel Multicore Sampling 

### ISSUE THREAD

**Issue by allrtaken** [meelgroup/unigen#2]
Hi,

Is it possible to enable the latest Unigen to take advantage of multi-core processors like it was possible for Unigen2? I tried setting
> --th=8

but CPU usage indicated that only one core was being used throughout. I need to generate a lot of samples so it would really speed things up if it were possible to parallelize.

Thanks!

**Comment by msoos** [comment]
Ah, sorry, this was a bug. The number of threads is not supported in this way, I now removed the option. Instead, please run with different seeds, manually. So for example:

```
$ ./unigen blasted_case110.cnf.gz.no_w.cnf  --samples 50 --verb 0 --sampleout mysamples_thread1 -s 1 &
$ ./unigen blasted_case110.cnf.gz.no_w.cnf  --samples 50 --verb 0 --sampleout mysamples_thread2 -s 2 &
$ ./unigen blasted_case110.cnf.gz.no_w.cnf  --samples 50 --verb 0 --sampleout mysamples_thread3 -s 3 &
```

For running on 3 cores. Then you can combine the samples from mysamples_thread1..3 into a single file, e.g. : `cat mysamples_thread* > all_samples` and you are done :)

I hope this helped,

Mate
