### ISSUE TITLE
Low verbosity mode

### ISSUE THREAD

**Issue by allrtaken** [meelgroup/unigen#3]
Hi,

I was wondering if its possible to have unigen write minimal amount of progress info to stdout (maybe something like number of solver invocations left or number of samples generated out of total requested, at periodic intervals). Currently, even with
> --verb=0

the number of lines in the output gets too large if a lot of samples (~5000) are requested, and its hard to make sense of the fast scrolling output to estimate how much progress has been made. I tried playing with different values for verbosity, but none seemed to help. Any pointers would be appreciated.

Thanks!

**Comment by msoos** [comment]
Hi,

Wow, nice catch! Sorry. It's now been fixed. You can get e.g. 5000 samples and have this be the full output:

```
$ ./unigen blasted_case110.cnf.gz.no_w.cnf  --samples 5000 --verb 0 --sampleout mysamples
c [unig] Time to sample: 2.13572 s -- Time count+samples: 2.22983 s
c [unig] Samples generated: 5049
```

Your samples are now in file `mysamples`. I hope this fixes the issue. Thanks again for pointing this out to us!

Mate
