### ISSUE TITLE
Using Unigen as a library and for Incremental Sampling

### ISSUE THREAD

**Issue by allrtaken** [meelgroup/unigen#4]
Hi,

What is the easiest way to call Unigen from my C++ code for retrieving samples directly instead of writing them to file first? Also, I would ideally like to generate samples on the fly without wasting time recomputing the startIteration and other overheads. Is there a way to do that?

Thanks!

**Comment by msoos** [comment]
Hey,

We may be able to do incremental sampling and I'll get back to you tomorrow
about this. However, it may not be faster at all. Sampling is not like
incremental SAT solving and the same ideas don't cleanly transfer, or
(mostly) don't transfer all all. Nevertheless I'll get back to you tomorrow
with an option that most likely will not be faster than doing it one by one.

I suggest you implement the normal, one by one way of doing this, though,
so you can compare speeds -- most likely the one-by-one will be faster
anyway.

Cheers,

Mate

**Comment by msoos** [comment]
Hey,

Please see the `main.cpp` file. Basically:

```
#include <unigen/unigen.h>
using namespace CMSat;
using namespace UniGen;
using std::cout;
using std::endl;

void mycallback(const std::vector<int>& solution, void*)
{
    for(uint32_t i = 0; i < solution.size(); i++) {
        cout << solution[i] <<  " ";
    }
     cout << "0" << endl;
}

int main () {
    auto appmc = new ApproxMC::AppMC;
    auto unigen = new UniG(appmc);
    appmc->set_verbosity(verbosity);
    unigen->set_callback(mycallback, NULL);
    vector<Lit> lits;

    appmc->add_variables(3);
    lits.clear();
    lits.push_back(Lit(0, true));
    lits.push_back(Lit(1, true));
    appmc->addClause(lits);

    auto sol_count = appmc->count();
    unigen->sample(&sol_count, num_samples);

    lits.clear();
    lits.push_back(Lit(0, true));
    lits.push_back(Lit(2, true));
    appmc->addClause(lits);

    sol_count = appmc->count();
    unigen->sample(&sol_count, num_samples);
    return 0;
}
```

**Comment by allrtaken** [comment]
Thanks a lot!

**Comment by msoos** [comment]
Glad to have helped! Please let us know if it worked :)

Mate
