### ISSUE TITLE
Error with --nosolext=0

### ISSUE THREAD

**Issue by andertavares** [meelgroup/unigen#6]
Hi, I'm using unigen to output samples for all variables (`--nosolext=0`), but it fails on `10.sk_1_46.cnf` from [this link](https://raw.githubusercontent.com/meelgroup/sampling-benchmarks/master/unigen-benchmarks/10.sk_1_46.cnf) with the following output to the terminal:

```
unigen: /home/anderson/code/unigen3/src/sampler.cpp:531:
std::vector<int> Sampler::get_solution_ints(const std::vector<CMSat::lbool>&): Assertion `model[var] != l_Undef' failed.
```

I executed the following command: `unigen --nosolext=0 /tmp/10.sk_1_46.cnf --sampleout=/tmp/out.txt`

It seems to me that the assertion failed because the value of some variable was undefined.

[edit: formatting]

**Comment by andertavares** [comment]
Update: the same error occurred with a file as small as that in the Readme:
```
c ind 1 3 4 6 7 8 10 0
p cnf 500 1
3 4 0
```
I saved that content as `/tmp/test.cnf` and ran: `unigen --nosolext 0 /tmp/test.cnf` and the same error occurred:

```
unigen: /home/anderson/code/unigen3/src/sampler.cpp:531: std::vector<int> Sampler::get_solution_ints(const std::vector<CMSat::lbool>&): Assertion `model[var] != l_Undef' failed.
Aborted (core dumped)
```
[edit: formatting ]

**Comment by msoos** [comment]
Ah, nice catch, thank you so much for the great test case and bug report! We forgot to automatically set `--forcesolextension 1` if `--nosolext=0` is set. Sorry about that. I now pushed a commit that should fix this. Let me know if this fixes your issue -- it fixes it for me.

Thanks again and thanks for using unigen!

Mate

**Comment by andertavares** [comment]
It seems to be working now, thank you very much!
